openapi: 3.0.1
info:
  title: LinTo-Platform-Disfluency
  description: Disfluency suppression
  contact:
    email: support@linto.ai
  license:
    name: AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 1.0.0
servers:
- url: /
paths:
  /disfluency:
    post:
      tags:
      - Disfluency API
      summary: Perform Disfluency Suppression
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                text:
                  type: string
                language:
                  type: string
      responses:
        200:
          description: Successfully transcribe the audio
          content: {}
        400:
          description: Request error
          content: {}
        500:
          description: Server error
          content: {}
  /healthcheck:
    get:
      tags:
      - Health
      summary: Check server health
      responses:
        200:
          description: Healthcheck passes
          content: {}
        400:
          description: Healthcheck fails
          content: {}
        500:
          description: Healthcheck fails
          content: {}
components: {}
