openapi: 3.0.0
info:
  version: 1.0.0
  title: LinTo-Platform-TBR-REPO_NAME
  description: TBR DEscription
  contact:
    email: support@linto.ai
  license:
    name: AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /TBR-service-route:
    post:
      tags:
        - TBR-SERVICE-TYPE API
      summary: TBR SUMMARY
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: TBR-DESCRIPTION
      responses:
        "200":
          description: Success
        "400":
          description: Request error
        "500":
          description: Server error
  /healthcheck:
    get:
      tags:
        - Health
      summary: Check server health
      responses:
        "200":
          description: Healthcheck passes
        "400":
          description: Healthcheck fails
        "500":
          description: Healthcheck fails
servers:
  - url: /